services:
  - name: restful-web-services
    type: web
    runtime: docker
    repo: https://github.com/SitnicCristina/restful-web-services
    plan: free
    region: oregon
    branch: main
    buildCommand: "java -version && ./mvnw clean package && ./mvnw liquibase:update"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: H2_CONSOLE_ENABLED
        value: "true"
    healthCheckPath: "/actuator/health"
