services:
  - name: restful-web-services
    type: web
    runtime: node
    repo: https://github.com/SitnicCristina/restful-web-services
    plan: free
    region: oregon
    branch: main
    buildCommand: "./mvnw clean package && ./mvnw liquibase:update"
    startCommand: "java -jar target/restful-web-services-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: H2_CONSOLE_ENABLED
        value: "true"
    healthCheckPath: "/actuator/health"
